### ISSUE TITLE
openLLM configuration issues

### ISSUE THREAD

**Issue by yananchen1989** [OSU-NLP-Group/TravelPlanner#14]
hi there,

for open models, such as `mistral`, `ChatGLM3-6B-32K` etc, in your code
https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/agents/tool_agents.py#L127,
why `model_name="gpt-3.5-turbo"` ?

may I know the reason ? thanks.

**Comment by hsaest** [comment]
Hi Yanan,

Thank you for your interest in our work. 

> LangChain uses OpenAI model names by default, so we need to assign some faux OpenAI model names to our local model.  

We use fastchat to deploy our local model, and you can see the details [here](https://github.com/lm-sys/FastChat/blob/main/docs/langchain_integration.md).

Feel free to contact us if you have further questions.

Best,
Jian

**Comment by yananchen1989** [comment]
thanks a lot.
