### ISSUE TITLE
bug in load_tools 

### ISSUE THREAD

**Issue by yananchen1989** [OSU-NLP-Group/TravelPlanner#15]
hello,

this may be a bug:
in agents/tool_agents.py, function `load_tools(self, tools: List[str], planner_model_name=None)`

should it be changed like this below ?
![image](https://github.com/OSU-NLP-Group/TravelPlanner/assets/26405281/50000310-b51e-4fc8-a7be-53a427c6eb0e)

because in your original manner, `model_name=planner_model_name` will not take effect when you want to pass in a `planner_model_name` which is not the same with the default setting (in class planner: `model_name: str = 'gpt-3.5-turbo-0125'`)

fyi.
thanks.

**Comment by yananchen1989** [comment]
i tested my change, seems that it passed.

**Comment by hsaest** [comment]
Hello,

In the original manner, the defualt model (i.e., gpt-3.5-turbo) will be replaced by the passed model (e.g., mistral). It can work then. Not sure why ‘not take effect’? 

Seems your way is more elegant. We will fix it ASAP.

**Comment by yananchen1989** [comment]
ok .. yeah i see.
in your original way, the planner tool will be initialized twice : first time with default llm. second time with specific llm passed.

hmm, that is fine. 
thanks for your reply.

**Comment by yananchen1989** [comment]
@hsaest  by the way, do you have any wechat group for the discussion of this project ?
thanks.

**Comment by hsaest** [comment]
@yananchen1989 

haha. we dont have any wechat groups. You can use email to get in touch with us. we will reply ASAP :).
