### ISSUE TITLE
Error in API doc

### ISSUE THREAD

**Issue by yitianlian** [OSU-NLP-Group/TravelPlanner#17]
![image](https://github.com/OSU-NLP-Group/TravelPlanner/assets/91449279/1f5494e5-5ac1-4754-89fd-167bffc4cea3)
![9156d723f298b3a433c4df1823a24f0](https://github.com/OSU-NLP-Group/TravelPlanner/assets/91449279/a3605f70-de2d-42d3-ac6e-59904b23dbb8)
The API description is inconsistent with the description in this Dict.

**Comment by hsaest** [comment]
have fixed it. Thank you!
