### ISSUE TITLE
您好，这边连不了外网，database链接下载不了里面的数据文件？能否提供一个国内可以下载的地址？

### ISSUE THREAD

**Issue by 13416157913** [OSU-NLP-Group/TravelPlanner#22]
您好，这边连不了外网，database链接（https://drive.google.com/file/d/1pF1Sw6pBmq2sFkJvm-LzJOqrmfWoQgxE/view?usp=drive_link）下载不了里面的数据文件？能否提供一个国内可以下载的地址？

**Comment by hsaest** [comment]
链接: https://pan.baidu.com/s/1Mwc9yBYGED185gKD36GakA?pwd=adky 提取码: adky 
您可以用百度网盘进行下载。

**Comment by 13416157913** [comment]
> 链接: https://pan.baidu.com/s/1Mwc9yBYGED185gKD36GakA?pwd=adky 提取码: adky 您可以用百度网盘进行下载。

thank you very much.

**Comment by 13416157913** [comment]
> 链接: https://pan.baidu.com/s/1Mwc9yBYGED185gKD36GakA?pwd=adky 提取码: adky 您可以用百度网盘进行下载。

您好，请问可否再提供一下osunlp/TravelPlanner这个数据集的下载链接？

**Comment by hsaest** [comment]
> > 链接: https://pan.baidu.com/s/1Mwc9yBYGED185gKD36GakA?pwd=adky 提取码: adky 您可以用百度网盘进行下载。
> 
> 您好，请问可否再提供一下osunlp/TravelPlanner这个数据集的下载链接？

链接: https://pan.baidu.com/s/1FXPT9K9R0-jT8100TeYD3Q?pwd=vbce 提取码: vbce

**Comment by 13416157913** [comment]
> > > 链接: https://pan.baidu.com/s/1Mwc9yBYGED185gKD36GakA?pwd=adky 提取码: adky 您可以用百度网盘进行下载。
> > 
> > 
> > 您好，请问可否再提供一下osunlp/TravelPlanner这个数据集的下载链接？
> 
> 链接: https://pan.baidu.com/s/1FXPT9K9R0-jT8100TeYD3Q?pwd=vbce 提取码: vbce

非常感谢！
