### ISSUE TITLE
Can you open-source the evaluation results of GPT4?

### ISSUE THREAD

**Issue by kleinzcy** [OSU-NLP-Group/TravelPlanner#28]
Hi, it is a great work to evaluate the LLM's ability in complex reasoning. can you opensource an log for GPT4 which sucessfully make a plan?

**Comment by hsaest** [comment]
Hi,

Thank you for your interest in our work and sorry for the delayed reply.

Please refer to [this](https://huggingface.co/datasets/osunlp/TravelPlanner/resolve/main/example_submission.jsonl?download=true) for GPT-4-Turbo generated plans on val set.

Feel free to contact us if you have further questions.

Best,
Jian
