### ISSUE TITLE
Process of collecting the dataset from publicly available information

### ISSUE THREAD

**Issue by Soumyabrata2003** [OSU-NLP-Group/TravelPlanner#29]
Hi,
First of all, great work ! 
I just wanted to know how you are collecting the data files like attractions.csv or clean_flights_2022.csv etc. Our group wants to curate such a dataset for a different country, so we were wondering which websites or how you are procuring the data.

**Comment by hsaest** [comment]
Hi,

Thanks for your interest in our work.

You could refer to Appendix A.3 of our paper, where we provide the details.

Feel free to contact us if you have further questions.

Best,
Jian

**Comment by Soumyabrata2003** [comment]
Hi, 
Just another thing: How do you make the dataset for TravelPlanner's train/ val or test set? Do you manually make the natural language queries or get it from some website? And, do you generate the columns from the of the dataset by parsing the natural language query using GPT-4? 

For train set, there is an "annotated_plan" column which is done manually as per your website. What is the use of "reference_information" column and how do you get that?

**Comment by hsaest** [comment]
Hi,

For natural language query generation, please refer to Section 3.3 - Query Construction. We also provide codes [here](https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/utils/query_element_selection.py).

The "annotated_plan" is created by human annotators. We required the annotators to use tools for information gathering, and the information that ultimately contributes to the annotated plan is provided as "reference_information".
