### ISSUE TITLE
Question about other LLMs

### ISSUE THREAD

**Issue by gaokaiz2** [OSU-NLP-Group/TravelPlanner#31]
Hi, I wonder whether your code works with other LLMs, specifically Gemini 1.5 Flash (which also can work with an API key)? And if so, how can I implement it?

**Comment by hsaest** [comment]
Yes, it can work with other LLMs. If you use LangChain, you only need to add the implementation [here](https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/agents/tool_agents.py#L141). The version may have changed, so please refer to the official LangChain documentation.
