### ISSUE TITLE
The purpose of providing fine-tuned models

### ISSUE THREAD

**Issue by resistzzz** [OSU-NLP-Group/TravelPlanner#32]
您好，我发现你们提供了两个SFT后的模型，想要请问一下你们SFT的训练数据是什么？

是TravelPlanner中的training set么，但是这个trainning set只有45条数据，这些数据用来构建few-shot in-context的示例是足够的，但是用于SFT Llama-8B是不是少了一些。

再次感谢作者的contributions!!

**Comment by hsaest** [comment]
Hi,

Thank you for your question. For the benefit of researchers worldwide, I respond in English here.

Yes, both models are fine-tuned to the training set, and no extra data is included. It is provided for quick reference when follow-up work requires reporting the performance of fine-tuned models or conducting more detailed analysis in planning tasks. 

This is intended to provide convenience, but it does not imply that we are specifically proposing these models for planning or other purposes.

Feel free to contact us if you have further questions.

Best,
Jian

**Comment by yananchen1989** [comment]
thanks for the sft model. quite valuable. 

looking forward the training script and sft dataset. 

just want to have a comparison with mine.

**Comment by resistzzz** [comment]
Thank you for your quick response.

quite valuable!
