### ISSUE TITLE
Some questions about the self-driving and taxi

### ISSUE THREAD

**Issue by resistzzz** [OSU-NLP-Group/TravelPlanner#33]
Hello,

I have some questions about the self-driving and taxi information.

During two-stage setting, we need to find information from the database, but there are no self-driving or taxi informations in the database? Perhaps I don't find them.

In the GoogleDistance, there are only distances between two cities, not contain the self-driving or taxi.

However, during the sole-plan setting, I find that there are self-driving or taxi informations in the "reference_information".

So could you give me some assistance to understand this point?

Thank you for your kind support.

**Comment by hsaest** [comment]
Hi,

If I understand correctly, you want to know how we provide the "cost" for self-driving and taxis. In order to fix the costs, we set the costs by hard rules. You can find the details [here](https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/tools/googleDistanceMatrix/apis.py#L30).

Please correct me if I misunderstood your question, and feel free to contact us if you have further questions.

Best,
Jian

**Comment by resistzzz** [comment]
Thank you very much!

I think I have understood now. In this environment, we can search from the Google distance to form the self-driving and taxi.
The cost of self-driving is equal to "distance * 0.05".
The cost of taxi is eual to "distance * 1.0"
If the driving duration between the two cities is longer than one day, we can not use self-driving and taxi as the transporation between these two cities.

Additonally, flight, self-driving, taxi are three kinds of transportations in this environment. In the final plan, we use one of them to travel between two cities. 

Is my understanding correct?

**Comment by resistzzz** [comment]
By the way, I ask another little question.

In the database of accommodation, the room type contains "Entire home/apt".
What "apt" means in this description?

Thank you very much!

**Comment by hsaest** [comment]
Hi,

Sorry for the delayed reply.

Your understanding is correct.  “apt” is short for “apartment，” and it is commonly used on rental platforms like Airbnb. And as you see in our paper, the accommodation information is adapted from the airbnb dataset public on Kaggle.
