### ISSUE TITLE
Issue in testing file thorugh Hugging face platform

### ISSUE THREAD

**Issue by lihkinVerma** [OSU-NLP-Group/TravelPlanner#34]
I am finding some issues with testing of attaching files - Split: "test", Eval mode: "sole-planning".

I have checked them with format_check.py before putting on Leaderboard and none of the files showed any errors/recommendations, as evident from following printed logs

Flights API loaded.
Accommodations loaded.
Restaurants loaded.
GoogleDistanceMatrix loaded.
Attractions loaded.
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [13:54<00:00,  1.20it/s]

Can you please let me know, what are the errors in testing these files from the leaderboard's backend. 

I tested files between 4:00-4:30 PM EDT on Oct-5.

I can resend the files as well through email.

**Comment by hsaest** [comment]
Hi Nikhil

I have addressed this issue via email. Feel free to contact us if you have further questions:)
