### ISSUE TITLE
How can I test my own method on this benchmark ?

### ISSUE THREAD

**Issue by flatLying** [OSU-NLP-Group/TravelPlanner#35]
My method is based on gpt-3.5-turbo, and i wanna test it on this benchmark? Could you please instruct me how to do it. How to custom the evaluation process. Thanks a lot !

**Comment by flatLying** [comment]
for example, my method can be used in the form of :
```
reasoner = CustomReasoner()
response = reasoner.reason(query)
```
How can it be tested in your benchmark, thanks

**Comment by hsaest** [comment]
Hi,

Thank you for your interest in our work. Please save the responses to a file and then follow [this](https://github.com/OSU-NLP-Group/TravelPlanner?tab=readme-ov-file#evaluation). Before evaluation, ensure that you have processed these responses in JSON format and that the file format adheres to our [guidelines](https://huggingface.co/spaces/osunlp/TravelPlannerLeaderboard).
