### ISSUE TITLE
Is it possible to replicate your work without using Google API?

### ISSUE THREAD

**Issue by Luyunfei0728** [OSU-NLP-Group/TravelPlanner#36]
Thank you for your amazing work on this project! I am currently trying to replicate your work but encountered a challenge regarding the use of Google API.
I would like to know:
1.Is it possible to replicate your work without using Google API?
2.If so, could you please provide guidance or alternative steps to achieve this?

**Comment by hsaest** [comment]
Hi,

It's OK to remove Google APIs.  Just remove [lines 141 - 143 in the file](https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/agents/tool_agents.py#L141-L143) if you don't want to test Google's models.

**Comment by Luyunfei0728** [comment]
Flights API loaded.
Accommodations loaded.
Restaurants loaded.
GoogleDistanceMatrix loaded.
Attractions loaded.
PlannerAgent mixtral loaded.
  0%|                                                                                                                                                             | 0/180 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/mnt/disk1/lyf/git/TravelPlanner/tools/planner/sole_planning.py", line 106, in <module>
    reference_information = query_data['reference_information']
KeyError: 'reference_information'


I wanted to inquire about the following error. After checking the data, I confirmed that the specified field does not exist. Has there been an issue with the dataset?
Thank you for your assistance.

**Comment by hsaest** [comment]
The code appears to be working well in my tests. Perhaps the dataset in your cache is corrupted. Could you please redownload the dataset by setting force-redownload?`query_data_list  = load_dataset('osunlp/TravelPlanner','validation',download_mode="force_redownload")['validation']`
