### ISSUE TITLE
Error during experiment reproduction: APIError with system_message undefined

### ISSUE THREAD

**Issue by Luyunfei0728** [OSU-NLP-Group/TravelPlanner#39]
Hi,

I encountered an error while trying to reproduce your experiment. The error message I received is as follows:

<locals>._completion_with_retry in 4.0 seconds as it raised APIError: Invalid response object from API: '{"object":"error","message":"\'system_message\' is undefined","type":"BadRequestError","param":null,"code":400}' (HTTP response code was 400).
APIError
To resolve this, I added a SystemMessage to my code, but I'm not sure if this change will affect the final results. Here's the modified code I used:

request = format_step(self.llm([SystemMessage(content=""),HumanMessage(content=self._build_agent_prompt())]).content)
Could you please take a look and let me know if this change is appropriate, or if there's something I might have missed? Any guidance would be appreciated!

Thank you!

**Comment by Luyunfei0728** [comment]
I would also like to kindly ask if the prompts used in the project are primarily assembled and called within the HumanMessage? And is the SystemMessage used rarely or almost never?

**Comment by hsaest** [comment]
Hi,

Thanks for your interest in our work first.

For Question 1: In my test, there's no need to provide the SystemMessage. Could you please provide more details, such as the models you used and the versions of Langchain and OpenAI?

For Question 2: We didn't use SystemMessage in our API requests, and all the prompts we used are primarily assembled and called within the HumanMessage.

**Comment by Luyunfei0728** [comment]
I am using langchain version 0.1.4, openai version 1.58.1, and the Mistral-7B-Instruct model deployed with vllm. Could it be an issue related to vllm? Regarding your response to the second question, it seems I can directly set the SystemMessage to be empty without affecting the results.

**Comment by hsaest** [comment]
You can try it. Feel free to contact us if you encounter any issues.

**Comment by Luyunfei0728** [comment]
Sorry to bother you again, but I still have some doubts about the evaluation results. Should the operation to process the results be executed from the Postprocess step and then submitted to Hugging Face? Thank you very much for your patient reply.

**Comment by hsaest** [comment]
Yes, please follow the instructions [here](https://github.com/OSU-NLP-Group/TravelPlanner?tab=readme-ov-file#postprocess). If you want to evaluate the test set, please use our hugging face leaderboard. Both offline and hugging face leaderboards can be used to evaluate the val set.

**Comment by Luyunfei0728** [comment]
Thank you very much for your patient reply.
