### ISSUE TITLE
Plan Parsing and Element Extraction Code

### ISSUE THREAD

**Issue by JasonZhu1313** [OSU-NLP-Group/TravelPlanner#6]
Looks like we need this code to submit result in leaderboard, do we have ETA on when this code can be released? Thanks

**Comment by hsaest** [comment]
Hi Jason,

Thank you for your interest in our work. We will release the parsing and extraction code in 3 days. Please look forward to it.

Best,
Jian

**Comment by JasonZhu1313** [comment]
Thanks, looking forward to it
