### ISSUE TITLE
Minor issues in the prompts

### ISSUE THREAD

**Issue by bamos** [OSU-NLP-Group/TravelPlanner#7]
Hi! I was quickly looking through the prompts and may have noticed a few minor issues in them:

1. The in-context example [here](https://github.com/OSU-NLP-Group/TravelPlanner/blob/b8e48bfb9a9787173063f11a97fead655e209fc1/agents/prompts.py#L70C20-L70C39) and in other prompts has the wrong flights. The query asks for Roanoke to Illinois, but the travel plan uses Ithaca to Charlotte:

![image](https://github.com/OSU-NLP-Group/TravelPlanner/assets/707462/52c280d1-78aa-4600-a932-d5ecc93ab04a)

2. `CostEnquiry` is mis-spelled as `CostEuquiry` in a few places, like [here](https://github.com/OSU-NLP-Group/TravelPlanner/blob/b8e48bfb9a9787173063f11a97fead655e209fc1/agents/prompts.py#L145). (The call here also has the incorrect flights)

![image](https://github.com/OSU-NLP-Group/TravelPlanner/assets/707462/23210075-a98c-446a-b992-662d8bf172e9)

**Comment by hsaest** [comment]
Hi Brandon,

Thank you for your careful check. We have fixed these mirror errors. 

If you have any further questions, please contact us.

Best,
Jian
